name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Version info
        run: |
          zig version
          echo "PWD: $(pwd)"
          ls -la
          echo "--- src/ contents ---"
          ls -la src/
          echo "--- tests/ contents ---"
          ls -la tests/

      - name: Run tests with verbose output
        run: zig build test --verbose
        env:
          CI: true

      - name: Check formatting
        run: zig fmt --check src/
